name: Push to AUR

on:
  push:
    branches:
      - master

jobs:
  PushToAUR:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    
    - name: Push aur/master
      run: git push aur master
